project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    toc: true
    toc-location: left
    comments:
      hypothesis: true
    reference-location: margin
    citation-location: margin
    citations-hover: true
    crossrefs-hover: true
    highlight-style: ayu-mirage
    include-in-header:
      - file: _headers/mathjax.html
  pdf:
    include-in-header:
      - file: _headers/preamble.tex
  docx: default
  jats: default

execute:
  freeze: auto
  echo: false
  warning: false
  message: false
